from .ext_sir_full import ExtendedSIRModelFull
from .ext_sir_full_no_diff import ExtendedSIRModelNoDiff
from .ext_sir_htucker import ExtendedSIRModelHTucker
from .ext_sir_htucker_no_diff import ExtendedSIRModelHTuckerNoDiff
from .sir_classic import SIRClassic
